# Uncomment the 'shield: nice_view' lines below if you are using nice!view displays.
# Additionally, you should enable the display feature in 'config/blecorne.conf'.
---
include:
  - board: blecorne_left
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    # shield: nice_view
  - board: blecorne_right
    # shield: nice_view
