# Uncomment the 'shield: nice_view' lines below if you are using nice!view displays.
# Additionally, you should enable the display feature in 'config/blecorne.conf'.
---
include:
  - board: blecorne_left
    snippet: studio-rpc-usb-uart
  - board: blecorne_right
